### ISSUE TITLE
Orientation at the centre of QR codes

### ISSUE THREAD

**Issue by pearlmary** [TemugeB/QR_code_orientation_OpenCV#1]
Thanks for the amazing post and code.

If I want to find the orientation of the QR code at the centre of the detected bounding box, what changes should I make in this?

![image](https://user-images.githubusercontent.com/29123795/175844643-26a99450-7f7b-44eb-a916-961ebf2a6d47.png)

**Comment by TemugeB** [comment]
Hi,

Not sure what you're exactly asking for. You just want to know the center coordinate? In that case, it is just the mean value of the 4 detected corner points. You can find it like this:

```python
center = np.mean(points.reshape((4,2)), axis = 0).astype(np.int32)
cv.circle(img, tuple(center), 3, (0,0,255), -1)
```

Where points is the returned corner points (line 59). The second line simply draws the center on the image. You can put these two lines after line 62. It should look like this. 

![image](https://user-images.githubusercontent.com/36071915/175849787-0aecc2bd-4245-4dfa-ac79-0e1de476913e.png)

**Comment by TemugeB** [comment]
If you want to just draw the axes at the center, then just add the proper shift. Change line 41 to:

al = 0.3 #axis length
unitv_points = np.array([[0,0,0], [al,0,0], [0,al,0], [0,0,al]], dtype = 'float32').reshape((4,1,3))
unitv_points = unitv_points + np.array([0.5,0.5,0.0]).reshape((1,1,3))

![image](https://user-images.githubusercontent.com/36071915/175850231-827da047-b24c-4b40-89e0-c54ee068f620.png)

**Comment by pearlmary** [comment]
> 

This is what I needed. Lots of thanks to you.

**Comment by pearlmary** [comment]
![image](https://user-images.githubusercontent.com/29123795/175891595-b7c623f6-de39-411d-848d-bc972779404d.png)
Can we also get the orientation angles in degrees like the one above from this code?

**Comment by TemugeB** [comment]
Line 62 returns rvec and tvec. Like your image, tvec is the position of the QR code pattern. Rvec is the rotation matrix (in Rodrigues vector form). If you want XYZ angles, then you need to decompose the rotation matrix into angles.  

You need to do something like this:
```python
R = cv.Rodrigues(rvec)

def Decompose_R_ZYX(R):

    #decomposes as RzRyRx. Note the order: ZYX <- rotation by x first
    thetaz = np.arctan2(R[1,0], R[0,0])
    thetay = np.arctan2(-R[2,0], np.sqrt(R[2,1]**2 + R[2,2]**2))
    thetax = np.arctan2(R[2,1], R[2,2])

    return thetaz, thetay, thetax

 thetaz, thetay, thetax = Decompose_R_ZYX(R)
```

Although I don't remember if rvec is Rodrigues form or 3x3 matrix form. Just make sure it is 3x3 matrix before calling the decompose function. Also, notice that this is X rotation first. Any other rotation order requires a different decomposition.

**Comment by pearlmary** [comment]
> Line 62 returns rvec and tvec. Like your image, tvec is the position of the QR code pattern. Rvec is the rotation matrix (in Rodrigues vector form). If you want XYZ angles, then you need to decompose the rotation matrix into angles.
> 
> You need to do something like this:
> 
> ```python
> R = cv.Rodrigues(rvec)
> 
> def Decompose_R_ZYX(R):
> 
>     #decomposes as RzRyRx. Note the order: ZYX <- rotation by x first
>     thetaz = np.arctan2(R[1,0], R[0,0])
>     thetay = np.arctan2(-R[2,0], np.sqrt(R[2,1]**2 + R[2,2]**2))
>     thetax = np.arctan2(R[2,1], R[2,2])
> 
>     return thetaz, thetay, thetax
> 
>  thetaz, thetay, thetax = Decompose_R_ZYX(R)
> ```
> 
> Although I don't remember if rvec is Rodrigues form or 3x3 matrix form. Just make sure it is 3x3 matrix before calling the decompose function. Also, notice that this is X rotation first. Any other rotation order requires a different decomposition.

Thank you so much for your timely reply.

**Comment by TemugeB** [comment]
Hopefully that helped. I'm closing this issue.
