### ISSUE TITLE
distance measure mismatch with the manual calculation

### ISSUE THREAD

**Issue by pearlmary** [TemugeB/QR_code_orientation_OpenCV#3]
Hi TemugeB,

Thanks again for your support, this code and blog.

I need some clarifications:

When I took the image at 30cm distance, the distance calculation using tvec i.e. distance = np.sqrt(np.sum(np.square(tvec))) is not matching. It gave me a result of 5.

My tvec results [[-0.70688058], [-1.48501116], [ 4.8272738 ]], for this image.
![image](https://user-images.githubusercontent.com/29123795/178405778-158b1657-9ddc-4e29-938d-8d2297721e3e.png)

I know that using Triangle Similarity for Object/Marker to Camera Distance, we can find it. But using tvec, or directly from this code, is there a way?

Can you guide/brief me?

**Comment by TemugeB** [comment]
The distance is in units of QR pattern size. So multiply by the size of your QR pattern. In other words, multiply 5 * x, where x is the length shown below.

![image](https://user-images.githubusercontent.com/36071915/178407559-d68b0632-3d3a-4710-a931-535b80113302.png)

Please don't create new issues, instead update the old issue with your questions. I will still see your comment even if the issue is closed.

**Comment by pearlmary** [comment]
The above measurement works well for camera image. I get 5*7cm which is correct. One weird thing I noticed is that while using the same code in the live video, without even multiplying by 7, I get the exact 35. 
Why the same distance measurement acts so in both still image and camera input video?. Do you have any documents that I can refer to for tvec.
Please help

**Comment by TemugeB** [comment]
The code uses [cv.solvePnP](https://docs.opencv.org/3.4/d9/d0c/group__calib3d.html#ga549c2075fac14829ff4a58bc931c033d:~:text=%E2%97%86-,solvePnP(),-bool%20cv%3A%3AsolvePnP) to obtain rvec and tvec. Rvec and tvec are just rotation matrix and translation vector in 3D. This is simple linear algebra and 2D example is shown [here](https://sites.millersville.edu/bikenaga/linear-algebra/transform/transform.html).

To calculate rvec and tvec, an assumption is made that the QR code side has a length of 1. So the measurement of tvec comes out in units of QR code length. So all you have to do is measure the side of the QR code with a tape measure and multiply with that number to obtain real world lengths.

I think what is happening with the live video is that your camera is roughly 35 units away from the QR code. So 35*7 should give you real world length.

**Comment by pearlmary** [comment]
Thanks for the update. 
Lastly, I have a doubt. I would be very much grateful, if you could guide me on this.
Instead of opencv inbuilt detector, if I use pyzbar library for corner detection,  will the object and image points change(or is it the same right hand coordinate system) for the solvepnp function. Little confusing.

Need help on this.

**Comment by TemugeB** [comment]
The axes directions can be decided by assigning coordinates to the detected corner points. You can change the point order to change the axes directions. See this line here: https://github.com/TemugeB/QR_code_orientation_OpenCV/blob/ad018c974750fb366ef44fff7a4202165d8e8855/run_qr.py#L32

**Comment by pearlmary** [comment]
Okay. Thanks a lot

**Comment by pearlmary** [comment]
Hi Temuge!
![image](https://user-images.githubusercontent.com/29123795/180167316-96fccf99-e254-4823-8758-9172c4654d30.png)
![image](https://user-images.githubusercontent.com/29123795/180167373-620b7611-7b1e-49cd-b647-a120b0b2b0e5.png)

The four corner points in the order of opencv QR detect function:
 [[[255.23985 227.5978 ]
  [359.39316 221.8115 ]
  [380.28568 315.27808]
  [261.79053 325.858  ]]]
The four-corner points order plotted in figure goes 4,3,2,1.
I want to know whether the order of corner coordinates and the object point coordinates are related in some way or the other?

Thanks for your help in Advance

**Comment by TemugeB** [comment]
It should be 1,2,3,4 order as shown in the bottom image. The output vector also looks to be in that order. So I don't know what the problem is.

**Comment by pearlmary** [comment]
The corner points in the first image in comparison to the second image, it looks 4,3,2,1 as per the points  [[[255.23985 227.5978 ], [359.39316 221.8115 ], [380.28568 315.27808],[261.79053 325.858 ]]]. Correct me if I'm wrong

**Comment by TemugeB** [comment]
The first point coordinates are [255,227], which is closest to top left. That is point 1, which is correct. I think you have a coding mistake when you put the coordinates on the image. The top left corner is considered origin for images.

**Comment by pearlmary** [comment]
Yes Temuge, I've marked wrongly. Thanks for the clarifications.

Once again thanks for all your help and speedy support.

**Comment by pearlmary** [comment]
> The code uses [cv.solvePnP](https://docs.opencv.org/3.4/d9/d0c/group__calib3d.html#ga549c2075fac14829ff4a58bc931c033d:~:text=%E2%97%86-,solvePnP(),-bool%20cv%3A%3AsolvePnP) to obtain rvec and tvec. Rvec and tvec are just rotation matrix and translation vector in 3D. This is simple linear algebra and 2D example is shown [here](https://sites.millersville.edu/bikenaga/linear-algebra/transform/transform.html).
> 
> To calculate rvec and tvec, an assumption is made that the QR code side has a length of 1. So the measurement of tvec comes out in units of QR code length. So all you have to do is measure the side of the QR code with a tape measure and multiply with that number to obtain real world lengths.
> 
> I think what is happening with the live video is that your camera is roughly 35 units away from the QR code. So 35*7 should give you real world length.
###################################################################################
 
Hi Temuge,

If we use SOLVEPNP_IPPE_SQUARE, The plane's 4 corners are defined as follows in object coordinates:
point 0: [-squareLength / 2.0, squareLength / 2.0, 0.0]
point 1: [squareLength / 2.0, squareLength / 2.0, 0.0]
point 2: [squareLength / 2.0, -squareLength / 2.0, 0.0]
point 3: [-squareLength / 2.0, -squareLength / 2.0, 0.0]
where squareLength denotes the length of the square. Therefore, the square is defined in object coordinates on the plane z=0 and centred at the origin.
---------------------------------------------------------------------
squareLength=1.0
SOLVEPNP_IPPE_SQUARE =7
qr_edges = np.array([[-squareLength / 2, squareLength / 2, 0.],
                              [ squareLength / 2, squareLength / 2, 0.],
                             [ squareLength / 2, -squareLength / 2, 0.],
                             [-squareLength / 2, -squareLength / 2, 0.]], dtype = 'float32').reshape((4,1,3))
ret, rvec, tvec = cv.solvePnP(qr_edges, points, cmtx, dist,flags = SOLVEPNP_IPPE_SQUARE)


In this case, should we multiply the real distance with 0.5 or 1 unit?


Thanks in advance.
