### ISSUE TITLE
Location of the camera from the new QR code coordinates

### ISSUE THREAD

**Issue by Matesanz** [TemugeB/QR_code_orientation_OpenCV#4]
Hello @TemugeB and **thank you** for such a **great and simple post!** :slightly_smiling_face: 

I have a doubt about **retrieving the camera position** in world coordinates. Copying from your post:

> If you need the position of the QR code with respect to the camera, then the position is saved in tvec. That is, the location of the QR code from the camera is tvec. On the other hand, if you need to location of the camera from the new QR code coordinates, then this can be calculated as:

```python
rvec, jacobian = cv.Rodrigues(rvec)
camera_position = -rvec.transpose() * tvec
```

:point_right:  The computed `camera_position` is a **3x3 matrix.**
:question: But how can it be "converted" to a **(x, y, z) vector**?

Nice regards! :slightly_smiling_face:

**Comment by TemugeB** [comment]
Oh you're right. The multiplication should be an ```@``` sign, meaning matrix multiplication. So it should be
```python
camera_position = -rvec.transpose() @ tvec
```

Thanks for pointing it out.
